### ISSUE TITLE
make master the default branch

### ISSUE THREAD

**Issue by mikey** [open-power/eCMD#1]
master-next is currently marked as the default branch.  

  https://github.com/open-power/eCMD/branches

Please change this to master.

**Comment by thejta** [comment]
Hi,

We have this set to master-next for the short term since anyone getting started we want to use eCMD 15.0.  Once the remaining work on 14.x (master) for current users is taken care of, we'll merge master-next to master and make master the default.

Any issue with that?  We're open to input on best practices.

**Comment by mikey** [comment]
If it was me, I would just call the 15.0 work master since that what you want people to use.  I'd have a second branch called ecmd-14.x that has that work and will be merged into master later.  I'd drop the name master-next as it doesn't make sense in this context (from what you wrote).

**Comment by mklight** [comment]
master is now the default branch
