### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by geissonator** [open-power/eCMD#350]
More of a feature request. OpenBMC builds the croserver into it's image. OpenBMC uses the upstream yocto distribution as it's base and they have removed all support for python2 and now only support python3.  We'll need tools like eCMD that we pull in to move as well.

Any chance this is on the list for things like config.py? Sometimes it's as easy as just changing the first line to "#!/usr/bin/env python3"

**Comment by thejta** [comment]
Does yocto not have a python->python3 link?  We hit a similar issue when fedora made python3 the default.  We updated the script to be compatible for both so the current `#!/usr/bin/env python` will work regardless of the python install.

**Comment by geissonator** [comment]
The direction I've seen is to not do that because you may end up with some weird undefined behavior. In general, python scripts are supposed to explicitly move to python3 to show they support it (and have tested it). I'm def not the expert though. Are you thinking eCMD is going to have to support both for a while? With python2 susnet (https://www.python.org/doc/sunset-python-2/), yocto just put the big hammer down and removed it completely.

We could probably put a little workaround in our croserver recipe and just replace the python with python3 in the config.py script if you feel like the support is there for it.

**Comment by geissonator** [comment]
Ahh, shoot, I ran into an issue with my workaround. config.py is using a deprecated python2 only option with platform:

```
| Establishing eCMD build variables..
| Determining host and distro..
| Traceback (most recent call last):
|   File "/home/andrewg/Code/openbmc/build/tmp/work/arm1176jzs-openbmc-linux-gnueabi/croserver/git-r0/git/config.py", line 373, in <module>
|     dtuple = platform.linux_distribution()
| AttributeError: module 'platform' has no attribute 'linux_distribution'
```

See https://docs.python.org/2/library/platform.html

**Comment by thejta** [comment]
eCMD still supports building on el6, which barely has python3 support.  So it's been a balancing act.  While the `env python` method isn't ideal, it has provided the most compatibility for users.

That said, you could try pulling this branch: https://github.com/thejta/eCMD/tree/update-config

That has both a hardcoded python3 call and updated logic to handle linux_distribution being pulled from python3.8.  The specific changeset is: https://github.com/thejta/eCMD/commit/28e306fb777681ffb9cfd6de293e3b29a174448a

It does require the distro module be available in the build environment, since that is the replacement for the deprecated function.

Adding @mklight and @kahnevan as they ultimately decide what goes in.  I just had a chance to hack this together.

**Comment by geissonator** [comment]
Thanks for the patch @thejta . Looks like yocto does not have a recipe for distro yet :(  I'll see what it takes to get one done.

**Comment by geissonator** [comment]
ok, I put a upstream recipe in via https://github.com/openembedded/meta-openembedded/pull/213 to get the Distro package.

@mklight or @kahnevan can we get the code from @thejta into master?

**Comment by thejta** [comment]
I put it up the branch a PR#361 for @mklight and @kahnevan to review/test

**Comment by klauskiwi** [comment]
Can we close this based on #361 merge?

**Comment by geissonator** [comment]
Yep, thanks for all the help guys, looks good!
