### ISSUE TITLE
pyecmd build broke on gmake 4.1

### ISSUE THREAD

**Issue by thejta** [open-power/eCMD#355]
When trying to build on boxes with gmake 4.1 today, the build broke:

```
pyeCMD Module x86_64 ...
makefile:16: *** Invalid file operation: </home/build/buildbase/p10/BUILD/ub1804/ecmd-src/ecmd-core/ext/cip/pyapi/cipClientPyapi.i.  Stop.
makefile:139: recipe for target 'pyecmd' failed
make[1]: *** [pyecmd] Error 2
makefile:60: recipe for target 'all' failed
make: *** [all] Error 2
```

The offending line is this:
```
HEADERS_TO_PARSE += $(foreach ext, $(EXT_PYAPI),$(if $(findstring $(ext)ClientCapi.H,$(file <$(EXT_$(ext)_PATH)/pyapi/$(ext)ClientPyapi.i)),$(EXT_$(ext)_PATH)/capi/$(ext)ClientCapi.H))
```

This broke on ubuntu 16.04, 18.04, debian 9 and fedora 30 and 31.  gmake 4.1 seems to be the common denominator on all machines.

**Comment by thejta** [comment]
I thought perhaps the `+=` assignment was tripping things up, so I did `:=` assign to a temp variable and then try to `+=` in the result.  That had no effect - still failed in the `:=` assignment

**Comment by mklight** [comment]
I think where I tested this with gnu make 3.81, the file command was not doing what was intended with https://github.com/open-power/eCMD/pull/325
switching from 
```
$(file < filename)
```
 to 
```
$(shell cat filename) 
```
I see it pulling more header files into the HEADERS_TO_PARSE variable
and now my make fails with new errors.

**Comment by mklight** [comment]
@fenkes-ibm is there a good way to restrict what generate_pyecmd.py uses from header files, specifically the fapi2ClientCapi.H? Should I just update `non_exported_names`?

**Comment by fenkes-ibm** [comment]
I think the most simple fix for make 4.1 is to put a space between the < and the file name - looks like make 4.1 is picky about that space being present. Or use $(shell cat filename) of course; I was just trying to avoid spawning a lot of subshells.

As for fapi2ClientCapi.H - the simple heuristic I'm using is "if <ext>ClientCapi.H is pulled into the SWIG .i file, it should be good enough for pyecmd too" which apparently fails for fapi2. Two short-term fixes come to mind:

1. Special-case fapi2 in the makefile to prevent it from being added to HEADERS_TO_PARSE
2. Add all the failing functions to `non_exported_names` as you propose, and throw in the getAttr functions for good measure since there's explicit support for them in `__init__.py`.

Long-term we should take a look at the failing functions and see if they can be made to work in pyecmd.

**Comment by thejta** [comment]
It tried it with a space between the < and the filename, it still failed in my tests.

**Comment by fenkes-ibm** [comment]
Okay, then $(shell cat filename) it is :)

**Comment by thejta** [comment]
This has been fixed at the master
